---
- hosts: control_plane
  become: yes
  vars:
      - user: "admin"
  tasks:
    - name: initialize the cluster
      shell:
        cmd: kubeadm init
      register: command_output
    - debug:
            var: command_output.stdout_lines

    - name: create .kube directory
      become: yes
      become_user: "{{user}}"
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/{{user}}/.kube/config
        remote_src: yes
        owner: "{{user}}"

    - name: Install git inorder to pull Nginx Ingress Controller
      apt:
        name: git
        state: present
        update_cache: yes

    - name: Taint All Nodes
      shell:
        cmd: kubectl taint nodes --all node-role.kubernetes.io/master-

    - name: install Pod network
      shell:
        cmd: kubectl apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml